# Generated by Django 3.2.4 on 2023-01-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional',
            field=models.TextField(default=''),
        ),
    ]
