# Generated by Django 3.2.4 on 2023-01-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='requestforsample',
            name='prod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.CreateModel(
            name='Talk_to_Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('company', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('prod', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
